-- MySQL Script generated by MySQL Workbench
-- Sat Mar 14 01:14:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cul d'Ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cul d'Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cul d'Ampolla` DEFAULT CHARACTER SET utf8 ;
USE `Cul d'Ampolla` ;

-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`proveïdor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`proveïdor` (
  `proveïdor_nif` CHAR(9) NOT NULL,
  `proveïdor_nom` VARCHAR(45) NULL,
  `proveïdor_adreça_carrer` VARCHAR(45) NULL,
  `proveïdor_adreça_numero` VARCHAR(45) NULL,
  `proveïdor_adreça_planta` VARCHAR(45) NULL,
  `proveïdor_adreça_porta` VARCHAR(45) NULL,
  `proveïdor_codi_postal` VARCHAR(10) NULL,
  `proveïdor_ciutat` VARCHAR(45) NULL,
  `proveïdor_pais` VARCHAR(45) NULL,
  `proveïdor_telefon` VARCHAR(45) NULL,
  `proveïdor_fax` VARCHAR(45) NULL,
  PRIMARY KEY (`proveïdor_nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`marcTipus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`marcTipus` (
  `marcTipus_id` INT NOT NULL,
  PRIMARY KEY (`marcTipus_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`ulleres` (
  `ulleres_id` INT NOT NULL,
  `ulleres_marca` VARCHAR(45) NULL,
  `ulleres_graduacio_esq` DECIMAL(4,2) NULL,
  `ulleres_graduacio_der` DECIMAL(4,2) NULL,
  `ulleres_tipus` VARCHAR(45) NULL,
  `ulleres_color_muntura` VARCHAR(45) NULL,
  `ulleres_color_vidre_esq` VARCHAR(45) NULL,
  `ulleres_color_vidre_der` VARCHAR(45) NULL,
  `ulleres_preu` DECIMAL(6,2) NULL,
  `proveïdor_proveïdor_nif` CHAR(9) NOT NULL,
  `marcTipus_marcTipus_id` INT NOT NULL,
  PRIMARY KEY (`ulleres_id`),
  INDEX `fk_ulleres_proveïdor_idx` (`proveïdor_proveïdor_nif` ASC) VISIBLE,
  INDEX `fk_ulleres_marcTipus1_idx` (`marcTipus_marcTipus_id` ASC) VISIBLE,
  CONSTRAINT `fk_ulleres_proveïdor`
    FOREIGN KEY (`proveïdor_proveïdor_nif`)
    REFERENCES `Cul d'Ampolla`.`proveïdor` (`proveïdor_nif`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ulleres_marcTipus1`
    FOREIGN KEY (`marcTipus_marcTipus_id`)
    REFERENCES `Cul d'Ampolla`.`marcTipus` (`marcTipus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`clients` (
  `clients_id` INT NOT NULL,
  `clients_nom` VARCHAR(45) NULL,
  `clients_adreça` VARCHAR(100) NULL,
  `clients_telefon` VARCHAR(15) NULL,
  `clients_correu_electronic` VARCHAR(45) NULL,
  `clients_data_registre` DATE NULL,
  `clients_client_recomanat` INT NULL,
  PRIMARY KEY (`clients_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`empleat` (
  `empleat_id` INT NOT NULL,
  `empleat_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`empleat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`ordre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`ordre` (
  `ordre_id` INT NOT NULL,
  `ulleres_ulleres_id` INT NOT NULL,
  `clients_clients_id` INT NOT NULL,
  `empleat_empleat_id` INT NOT NULL,
  PRIMARY KEY (`ordre_id`),
  INDEX `fk_ordre_ulleres1_idx` (`ulleres_ulleres_id` ASC) VISIBLE,
  INDEX `fk_ordre_clients1_idx` (`clients_clients_id` ASC) VISIBLE,
  INDEX `fk_ordre_empleat1_idx` (`empleat_empleat_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordre_ulleres1`
    FOREIGN KEY (`ulleres_ulleres_id`)
    REFERENCES `Cul d'Ampolla`.`ulleres` (`ulleres_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordre_clients1`
    FOREIGN KEY (`clients_clients_id`)
    REFERENCES `Cul d'Ampolla`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordre_empleat1`
    FOREIGN KEY (`empleat_empleat_id`)
    REFERENCES `Cul d'Ampolla`.`empleat` (`empleat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
